### ISSUE TITLE
Any plans to release pypy wheels for windows?

### ISSUE THREAD

**Issue by scottbelden** [milesgranger/cramjam#115]
Looks like there are pypy wheels for linux and macos, but not windows. Are there plans to release pypy wheels for windows?

**Comment by milesgranger** [comment]
Yes! I believe it's supported so why not. Will put it on my todo.

**Comment by scottbelden** [comment]
The original reason I was asking for this is because I was seeing the error in https://github.com/milesgranger/pyrus-cramjam/issues/116 on windows and assumed it was because it was building the package from source and not using a wheel. However, when I switched to pypy3.9 for windows I no longer get the Buffer error.

Using pypy3.9 looks like it works for all platforms for me.
