### ISSUE TITLE
lzma / xz support?

### ISSUE THREAD

**Issue by lgray** [milesgranger/cramjam#126]
Hi! 

Is it planned or already in the works to have lzma support in cramjam? 

A bunch of high energy particle physicists would be rather grateful for that capability in this package.

**Comment by milesgranger** [comment]
Hey there!

Good idea, this is the first request for it. Started work over in #127. Right now though it doesn't decode LZMA format, only XZ. If you're good with that, I'm happy to merge and make a development release in the meantime before fleshing out the rest of the details.

**Comment by lgray** [comment]
@milesgranger thanks, I'll give it a try soon and see if it's sufficient.

**Comment by milesgranger** [comment]
2.8.1-dev1 is on PyPI if that's useful for you. 
https://pypi.org/project/cramjam/2.8.1.dev1/#files

Might be some days before I have some free time to work out the rest of the api support I want here though.

**Comment by lgray** [comment]
@milesgranger Thanks for the dev release it was useful to prototype!
We try to keep a policy to not use pre-releases as dependencies in main releases of our packages.
What do you think would be the timeline to pop `lzma` out of experimental and make a non `.devN` release with lzma in?

Whatever is realistic is fine, really just for our own planning!

@jpivarski - FYI

**Comment by milesgranger** [comment]
Would you be okay leaving it in the experimental module? That'll take longer to move out of, a few weeks maybe. Otherwise I can make a release probably this weekend with the existing state.

**Comment by lgray** [comment]
@milesgranger Oh, the experimental namespace is fine, it's the `.devN` release that prevents us from using it right now.

I'm fine to take care of the dance of moving namespaces as that evolves.

**Comment by milesgranger** [comment]
On the way then! :+1: 
https://github.com/milesgranger/cramjam/actions/runs/7670394783
https://github.com/milesgranger/cramjam/releases/tag/v2.8.1

**Comment by lgray** [comment]
Ah, cool, thanks!

**Comment by jpivarski** [comment]
Since #127 is merged, this issue should be closed now, right? Unless you intend PR #133 to be the completion of this issue.

**Comment by lgray** [comment]
From our side this is complete. We should clean up the code and adjust associated pins once #133 is in!

**Comment by lgray** [comment]
Ah sorry - I thought this was in uproot somehow. I'll let Miles determine when we should close this. I'm not sure if the threshold is when it is out of `experimental` or not.

**Comment by milesgranger** [comment]
Ya okay, thanks for the feedback. 
I kinda plan on renaming it from lzma -> xz w/ ability to de/compress lzma but feels weird to name it something that is long deprecated. 

Then I'll probably remove all the filter logic stuffy stuff and move it out of experimental, so it'll be `cramjam.xz` module. 
Just need a bit of time to get to it. Thanks for the patience! :)
