### ISSUE TITLE
Please coordinate PyPI and crates.io releases if possible

### ISSUE THREAD

**Issue by musicinmybrain** [milesgranger/cramjam#130]
I’m almost at the point of introducing a `python-cramjam` package to Fedora Linux. I’m currently updating my proposed package from 2.8.0 to 2.8.1.

I am *able* to use bundled or vendored dependencies when I need to under our [packaging guidelines](https://docs.fedoraproject.org/en-US/packaging-guidelines/#bundling), but it’s preferred to build against system copies. I have already introduced a [`rust-libcramjam` package](https://src.fedoraproject.org/rpms/rust-libcramjam/), and I can build a `python-cramjam-2.8.0` package using it (in lieu of the copy included in the GitHub archive or PyPI sdist).

With 2.8.1, though, the included `libcramjam` is updated to 0.2.0, which hasn’t yet been released [on crates.io](https://crates.io/crates/libcramjam). I can temporarily switch to using the bundled `libcramjam` again, but it would make life easier if the version used by the Python extension were reliably available on crates.io. (Rust library crates that are published on crates.io are [required to be packaged from crates.io sources](https://docs.fedoraproject.org/en-US/packaging-guidelines/Rust/#_package_sources), so I can’t just package a snapshot from GitHub as `rust-libcrmjam`.)

What do you think? Does this sound reasonable?

**Comment by milesgranger** [comment]
wow, that's great, thanks for you work here! I'm blissfully unaware of things like this but more than happy to adjust to make it better.

For the time being, I've published the v0.2.0 of libcramjam to crates.io as it was at the v2.8.1 release of python cramjam. Then removing the relative path dependency to libcramjam in #131 which ought to make sure python's cramjam isn't released without libcramjam already on crates.io first.

**Comment by musicinmybrain** [comment]
> wow, that's great, thanks for you work here! I'm blissfully unaware of things like this but more than happy to adjust to make it better.

❤️ 

> For the time being, I've published the v0.2.0 of libcramjam to crates.io as it was at the v2.8.1 release of python cramjam.

Wonderful! Thank you.

> Then removing the relative path dependency to libcramjam in #131 which ought to make sure python's cramjam isn't released without libcramjam already on crates.io first.

That is even better than I had thought to ask for, and will save me a (small) downstream patch in future releases.
