### ISSUE TITLE
cramjam 2.8.1 release on conda?

### ISSUE THREAD

**Issue by lgray** [milesgranger/cramjam#139]
Presently only 2.8.0 is present on conda, when you have time, could you please update it? 

This is blocking https://github.com/conda-forge/uproot-feedstock/pull/144 since the dependency doesn't yet exist.

**Comment by milesgranger** [comment]
Ya, I'm usually good about keeping them online but notice conda is both longer and more fickle in the build process. On this one osx failed with some symbol errors but trying it again now.

https://github.com/conda-forge/cramjam-feedstock/pull/36/checks

Can be slightly tiresome trying to maintain two CI builds. 😅

**Comment by lgray** [comment]
No worries! Just doing my part to keep the stone rolling up this hill.

**Comment by milesgranger** [comment]
Looks like the same symbol errors happen. I'll try to find some time this weekend or early next week.

**Comment by milesgranger** [comment]
https://github.com/conda-forge/cramjam-feedstock/pull/36 in fixed, thanks for the reminder.
