### ISSUE TITLE
Unused `Cargo.lock` files?

### ISSUE THREAD

**Issue by mgorny** [milesgranger/cramjam#148]
I've noticed that in addition to the top-level `Cargo.lock` file, there are `Cargo.lock` files in individual directories. However, from what I can see `cargo` only uses the file from the workspace root, i.e. the top-level file, and the other files are unused. Am I missing something, or can they be removed?

**Comment by mgorny** [comment]
Ok, thanks, I take it that they no hidden purpose then ;-).

**Comment by milesgranger** [comment]
Ya, thanks for noticing and the report. 👍
