### ISSUE TITLE
Request: add recipe to emscripten-forge

### ISSUE THREAD

**Issue by ariostas** [milesgranger/cramjam#166]
Currently `cramjam` is being built as a [package for Pyodide](https://github.com/pyodide/pyodide/tree/main/packages/cramjam), but there is no recipe for `emscripten-forge`. It would be really nice to add this recipe so that one could have more options to use it on WASM. All that needs to be done is place a couple of files [here](https://github.com/emscripten-forge/recipes/tree/main/recipes/recipes_emscripten), which should be pretty much the same as what is already present in the [cramjam feedstock](https://github.com/conda-forge/cramjam-feedstock).

**Comment by milesgranger** [comment]
Sounds cool! I've got some other TODOs here in this project as well but I've been extra busy with family and work lately; many apologies.

**Comment by ariostas** [comment]
No worries, thanks so much!

**Comment by milesgranger** [comment]
xref: https://github.com/emscripten-forge/recipes/pull/1321
