### ISSUE TITLE
Add a pre-built binary for PyPy 3.9

### ISSUE THREAD

**Issue by Xuanwo** [milesgranger/cramjam#185]
Hi @milesgranger, thank you for creating this.

I'm from the Apache Avro community. We rely on `python-snappy`, which depends on `cramjam`. Our tests failed on PyPy 3.9 because `cramjam` doesn't have built PyPy 3.9 wheels.

For example: https://github.com/apache/avro/actions/runs/11230133902/job/31216914304

Although we could figure out how to build `cramjam` from source or stop testing on PyPy, I wanted to discuss with you first whether it's possible to provide PyPy-3.9 on PyPI. I'm willing to help implement the workflow.

**Comment by milesgranger** [comment]
Hi, many apologies. This was removed in #177 because I saw PyPy3.9 is no longer available? https://pypy.org/download.html

If this was a mistake, I'm fine to add it back; but as it's seemingly unmaintained is it possible to "just" upgrade to pypy3.10?

**Comment by Xuanwo** [comment]
Thank you for the quick response. It appears PyPy doesn't offer a pre-built PyPy-3.9 release since `PyPy version v7.3.17`: https://downloads.python.org/pypy/

The PyPy team explained the removal at https://pypy.org/posts/2024/08/pypy-v7317-release.html.

> The keen-eyed will have noticed no mention of Python version 3.9 in the releases above. Typically we will maintain only one version of Python3, but due to PyPy3.9 support on conda-forge we maintained multiple versions from the first release of PyPy3.10 in PyPy v7.3.12 (Dec 2022). Conda-forge is [sunsetting its PyPy support](https://pypy.org/posts/2024/08/conda-forge-proposes-dropping-support-for-pypy.html), which means we can drop PyPy3.9.

---

I will bring this discussion back to the Avro community to see if we can discontinue support for PyPy 3.9.

**Comment by milesgranger** [comment]
Sounds good; again I have no strong feelings against bringing it back w/ a post release if you run into any blockers on your end. :+1:
