### ISSUE TITLE
Add a `Cargo.lock` file

### ISSUE THREAD

**Issue by DanielNoord** [milesgranger/cramjam#191]
For https://github.com/milesgranger/cramjam/issues/148 it seems some `Cargo.lock` files were removed, but with the new project structure of >= `2.9.x` there is no longer a `Cargo.lock` file anywhere within the project.
This actually makes the package quite hard to package on downstream packagers as those tend to require a lock file.

See the relevant section in the `nix` guidelines:
https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/rust.section.md

Would it be possible to add a top-level `Cargo.lock` file again and do a release so we could package a version that supports Python 3.13 but is also packagable by the default infrastructure in `nix`?

**Comment by milesgranger** [comment]
Released v2.9.1
Thanks for informing me about this.

**Comment by DanielNoord** [comment]
Awesome, appreciate the quick fix!
