### ISSUE TITLE
Failed to build `cramjam==2.8.1` with the latest version of maturin

### ISSUE THREAD

**Issue by emdneto** [milesgranger/cramjam#195]
When installing cramjam==2.8.1 I'm receiving the following error:

```
$ pip install cramjam==2.8.1
Resolved 25 packages in 68ms
  × Failed to build `cramjam==2.8.1`
  ├─▶ The build backend returned an error
  ╰─▶ Call to `maturin.build_wheel` failed (exit status: 1)

      [stdout]
      Running `maturin pep517 build-wheel -i cache/uv/builds-v0/.tmpS13GpD/bin/python --compatibility off`

      [stderr]
      💥 maturin failed
        Caused by: `project.version` field is required in pyproject.toml unless it is present in the `project.dynamic` list
      Error: command ['maturin', 'pep517', 'build-wheel', '-i', 'cache/uv/builds-v0/.tmpS13GpD/bin/python', '--compatibility', 'off'] returned non-zero exit status 1

      hint: This usually indicates a problem with the package or the build environment.
 ```
 
since 1.8.0 [maturin](https://github.com/PyO3/maturin/pull/2391) throws an error if package does not specify version in pyproject.toml -> https://github.com/PyO3/maturin/releases/tag/v1.8.0
 
More context on my issue -> CI is failing here: https://github.com/open-telemetry/opentelemetry-python-contrib/actions/runs/12503550201/job/34884097964?pr=3134

**Comment by emdneto** [comment]
The error happens until 2.8.3. Build is fine from >= 2.8.4

**Comment by milesgranger** [comment]
Thanks, I'm curious though why you're building the wheel and not using the ones already available on PyPI? 

Secondly, and maybe most importantly, if >=2.8.4 build fine with the latest version of maturin then that's great. Otherwise when past versions of cramjam no longer build with the latest version of maturin then...well, I don't think I care at all. My recommendation there would be to build <2.8.4 with whatever version of maturin was used/available at that time.

**Comment by emdneto** [comment]
> Thanks, I'm curious though why you're building the wheel and not using the ones already available on PyPI?
> 
> Secondly, and maybe most importantly, if >=2.8.4 build fine with the latest version of maturin then that's great. Otherwise when past versions of cramjam no longer build with the latest version of maturin then...well, I don't think I care at all. My recommendation there would be to build <2.8.4 with whatever version of maturin was used/available at that time.

I'm just running: `pip install cramjam==2.8.1` as usual. CI is working fine with 2.8.4. Will close this then, Thanks.

**Comment by milesgranger** [comment]
Okay, if it's building from source due to there not being a wheel available for the platform then I'm quite interested as I'm trying to ensure pretty much all platforms have wheels built for them.  Or maybe you just need to ensure pip is upgraded before trying to install?
