### ISSUE TITLE
zlib-ng?

### ISSUE THREAD

**Issue by martindurant** [milesgranger/cramjam#95]
According to the flate2 crate's [README](https://github.com/rust-lang/flate2-rs#backends), you can opt to compile with zlib-ng for better performance. Is it a good idea?

**Comment by musicinmybrain** [comment]
It may interest you to know that Fedora Linux will not ship “classic” zlib at all beginning with Fedora 40; it [has been replaced system-wide](https://fedoraproject.org/wiki/Changes/ZlibNGTransition) with the `zlib-ng-compat` library.

I don’t have any specific insight into why you saw larger compressed output in your testing, although there is some discussion at https://github.com/zlib-ng/zlib-ng/issues/1656 that may or may not be enlightening.

**Comment by milesgranger** [comment]
Interesting, seems like it warrants another look then! thanks for the tip and link to the related issue. :+1:

**Comment by milesgranger** [comment]
Actually looking more into this, using the default Rust backend doesn't cause you any trouble with the work in packaging for Fedora, does it? I'm not interpreting your comment to serve as a warning about if we do switch to zlib-ng*; I'm inclined to close this and stick with the current Rust backend as it's been trouble free and good enough performance wise.

**Comment by musicinmybrain** [comment]
No, the status quo isn’t causing me any trouble. My comment should be interpreted as a mild vote of confidence in `zlib-ng` overall – it seems to be working out OK – and a warning to be aware that the system “zlib” may actually be `zlib-ng-compat` in some environments, so don’t assume that you’re always getting the original zlib even if you ”ask” for it.

The only difficulties we’ve encountered have been some projects with tests that check the exact bytes or block sizes in the compressed output. There was never a guarantee that zlib would always produce the same output with the same settings, but the compressor implementation made the same choices in practice for many years. The byte streams produced by `zlib-ng` or `zlib-ng-compat` are compatible, but not identical. We just help those projects loosen their tests’ expectations, or we skip the affected tests.

**Comment by milesgranger** [comment]
That makes sense, thanks for the clarification. :+1:
